<?php

// File generated from our OpenAPI spec

namespace Payske\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \Payske\Account::OBJECT_NAME => \Payske\Account::class,
        \Payske\AccountLink::OBJECT_NAME => \Payske\AccountLink::class,
        \Payske\AlipayAccount::OBJECT_NAME => \Payske\AlipayAccount::class,
        \Payske\ApplePayDomain::OBJECT_NAME => \Payske\ApplePayDomain::class,
        \Payske\ApplicationFee::OBJECT_NAME => \Payske\ApplicationFee::class,
        \Payske\ApplicationFeeRefund::OBJECT_NAME => \Payske\ApplicationFeeRefund::class,
        \Payske\Balance::OBJECT_NAME => \Payske\Balance::class,
        \Payske\BalanceTransaction::OBJECT_NAME => \Payske\BalanceTransaction::class,
        \Payske\BankAccount::OBJECT_NAME => \Payske\BankAccount::class,
        \Payske\BillingPortal\Configuration::OBJECT_NAME => \Payske\BillingPortal\Configuration::class,
        \Payske\BillingPortal\Session::OBJECT_NAME => \Payske\BillingPortal\Session::class,
        \Payske\BitcoinReceiver::OBJECT_NAME => \Payske\BitcoinReceiver::class,
        \Payske\BitcoinTransaction::OBJECT_NAME => \Payske\BitcoinTransaction::class,
        \Payske\Capability::OBJECT_NAME => \Payske\Capability::class,
        \Payske\Card::OBJECT_NAME => \Payske\Card::class,
        \Payske\Charge::OBJECT_NAME => \Payske\Charge::class,
        \Payske\Checkout\Session::OBJECT_NAME => \Payske\Checkout\Session::class,
        \Payske\Collection::OBJECT_NAME => \Payske\Collection::class,
        \Payske\CountrySpec::OBJECT_NAME => \Payske\CountrySpec::class,
        \Payske\Coupon::OBJECT_NAME => \Payske\Coupon::class,
        \Payske\CreditNote::OBJECT_NAME => \Payske\CreditNote::class,
        \Payske\CreditNoteLineItem::OBJECT_NAME => \Payske\CreditNoteLineItem::class,
        \Payske\Customer::OBJECT_NAME => \Payske\Customer::class,
        \Payske\CustomerBalanceTransaction::OBJECT_NAME => \Payske\CustomerBalanceTransaction::class,
        \Payske\Discount::OBJECT_NAME => \Payske\Discount::class,
        \Payske\Dispute::OBJECT_NAME => \Payske\Dispute::class,
        \Payske\EphemeralKey::OBJECT_NAME => \Payske\EphemeralKey::class,
        \Payske\Event::OBJECT_NAME => \Payske\Event::class,
        \Payske\ExchangeRate::OBJECT_NAME => \Payske\ExchangeRate::class,
        \Payske\File::OBJECT_NAME => \Payske\File::class,
        \Payske\File::OBJECT_NAME_ALT => \Payske\File::class,
        \Payske\FileLink::OBJECT_NAME => \Payske\FileLink::class,
        \Payske\Identity\VerificationReport::OBJECT_NAME => \Payske\Identity\VerificationReport::class,
        \Payske\Identity\VerificationSession::OBJECT_NAME => \Payske\Identity\VerificationSession::class,
        \Payske\Invoice::OBJECT_NAME => \Payske\Invoice::class,
        \Payske\InvoiceItem::OBJECT_NAME => \Payske\InvoiceItem::class,
        \Payske\InvoiceLineItem::OBJECT_NAME => \Payske\InvoiceLineItem::class,
        \Payske\Issuing\Authorization::OBJECT_NAME => \Payske\Issuing\Authorization::class,
        \Payske\Issuing\Card::OBJECT_NAME => \Payske\Issuing\Card::class,
        \Payske\Issuing\CardDetails::OBJECT_NAME => \Payske\Issuing\CardDetails::class,
        \Payske\Issuing\Cardholder::OBJECT_NAME => \Payske\Issuing\Cardholder::class,
        \Payske\Issuing\Dispute::OBJECT_NAME => \Payske\Issuing\Dispute::class,
        \Payske\Issuing\Transaction::OBJECT_NAME => \Payske\Issuing\Transaction::class,
        \Payske\LineItem::OBJECT_NAME => \Payske\LineItem::class,
        \Payske\LoginLink::OBJECT_NAME => \Payske\LoginLink::class,
        \Payske\Mandate::OBJECT_NAME => \Payske\Mandate::class,
        \Payske\Order::OBJECT_NAME => \Payske\Order::class,
        \Payske\OrderItem::OBJECT_NAME => \Payske\OrderItem::class,
        \Payske\OrderReturn::OBJECT_NAME => \Payske\OrderReturn::class,
        \Payske\PaymentIntent::OBJECT_NAME => \Payske\PaymentIntent::class,
        \Payske\PaymentMethod::OBJECT_NAME => \Payske\PaymentMethod::class,
        \Payske\Payout::OBJECT_NAME => \Payske\Payout::class,
        \Payske\Person::OBJECT_NAME => \Payske\Person::class,
        \Payske\Plan::OBJECT_NAME => \Payske\Plan::class,
        \Payske\Price::OBJECT_NAME => \Payske\Price::class,
        \Payske\Product::OBJECT_NAME => \Payske\Product::class,
        \Payske\PromotionCode::OBJECT_NAME => \Payske\PromotionCode::class,
        \Payske\Quote::OBJECT_NAME => \Payske\Quote::class,
        \Payske\Radar\EarlyFraudWarning::OBJECT_NAME => \Payske\Radar\EarlyFraudWarning::class,
        \Payske\Radar\ValueList::OBJECT_NAME => \Payske\Radar\ValueList::class,
        \Payske\Radar\ValueListItem::OBJECT_NAME => \Payske\Radar\ValueListItem::class,
        \Payske\Recipient::OBJECT_NAME => \Payske\Recipient::class,
        \Payske\RecipientTransfer::OBJECT_NAME => \Payske\RecipientTransfer::class,
        \Payske\Refund::OBJECT_NAME => \Payske\Refund::class,
        \Payske\Reporting\ReportRun::OBJECT_NAME => \Payske\Reporting\ReportRun::class,
        \Payske\Reporting\ReportType::OBJECT_NAME => \Payske\Reporting\ReportType::class,
        \Payske\Review::OBJECT_NAME => \Payske\Review::class,
        \Payske\SetupAttempt::OBJECT_NAME => \Payske\SetupAttempt::class,
        \Payske\SetupIntent::OBJECT_NAME => \Payske\SetupIntent::class,
        \Payske\Sigma\ScheduledQueryRun::OBJECT_NAME => \Payske\Sigma\ScheduledQueryRun::class,
        \Payske\SKU::OBJECT_NAME => \Payske\SKU::class,
        \Payske\Source::OBJECT_NAME => \Payske\Source::class,
        \Payske\SourceTransaction::OBJECT_NAME => \Payske\SourceTransaction::class,
        \Payske\Subscription::OBJECT_NAME => \Payske\Subscription::class,
        \Payske\SubscriptionItem::OBJECT_NAME => \Payske\SubscriptionItem::class,
        \Payske\SubscriptionSchedule::OBJECT_NAME => \Payske\SubscriptionSchedule::class,
        \Payske\TaxCode::OBJECT_NAME => \Payske\TaxCode::class,
        \Payske\TaxId::OBJECT_NAME => \Payske\TaxId::class,
        \Payske\TaxRate::OBJECT_NAME => \Payske\TaxRate::class,
        \Payske\Terminal\ConnectionToken::OBJECT_NAME => \Payske\Terminal\ConnectionToken::class,
        \Payske\Terminal\Location::OBJECT_NAME => \Payske\Terminal\Location::class,
        \Payske\Terminal\Reader::OBJECT_NAME => \Payske\Terminal\Reader::class,
        \Payske\ThreeDSecure::OBJECT_NAME => \Payske\ThreeDSecure::class,
        \Payske\Token::OBJECT_NAME => \Payske\Token::class,
        \Payske\Topup::OBJECT_NAME => \Payske\Topup::class,
        \Payske\Transfer::OBJECT_NAME => \Payske\Transfer::class,
        \Payske\TransferReversal::OBJECT_NAME => \Payske\TransferReversal::class,
        \Payske\UsageRecord::OBJECT_NAME => \Payske\UsageRecord::class,
        \Payske\UsageRecordSummary::OBJECT_NAME => \Payske\UsageRecordSummary::class,
        \Payske\WebhookEndpoint::OBJECT_NAME => \Payske\WebhookEndpoint::class,
    ];
}
